<a href="https://colab.research.google.com/github/Shranya24/ai_ml/blob/main/spamdetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer #text to numbers
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data colection and pre processing

In [67]:
raw_mail_data= pd.read_csv('/content/mail_data.csv')

In [68]:
#replace the null valules with null string
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [69]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

label encoding

In [70]:
#spam as 0 and ham as 1
mail_data.loc[mail_data['Category']== 'spam','Category', ] =0
mail_data.loc[mail_data['Category']== 'ham', 'Category',] = 1

In [71]:
mail_data.tail()

     Category                                            Message
5567        0  This is the 2nd time we have tried 2 contact u...
5568        1               Will ü b going to esplanade fr home?
5569        1  Pity, * was in mood for that. So...any other s...
5570        1  The guy did some bitching but I acted like i'd...
5571        1                         Rofl. Its true to its name

In [72]:
X= mail_data['Message']
Y= mail_data['Category']

In [73]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [74]:
Y= Y.astype('int') #object type to int for model fitting

In [75]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: int64

In [76]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [77]:
# transform the text data to feature vectors that can be used as input to the Logistic regression

feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

In [78]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34768 stored elements and shape (4457, 7458)>
  Coords	Values
  (0, 6927)	0.48935591439341625
  (0, 6586)	0.44333254982109394
  (0, 3958)	0.6161071828926097
  (0, 4334)	0.42941702167641554
  (1, 3168)	0.5869421390016224
  (1, 6971)	0.4281243465155688
  (1, 1428)	0.5869421390016224
  (1, 2121)	0.35736171430221464
  (2, 6878)	0.35749230587184955
  (2, 1876)	0.28751725124107325
  (2, 5894)	0.35749230587184955
  (2, 806)	0.26730249393705324
  (2, 5695)	0.35749230587184955
  (2, 4884)	0.35749230587184955
  (2, 3852)	0.3408491178137899
  (2, 7353)	0.31988118061968496
  (2, 5115)	0.3408491178137899
  (3, 1876)	0.3080768784015236
  (3, 7297)	0.22192369472149484
  (3, 7000)	0.30072945056088285
  (3, 7065)	0.32795623716393424
  (3, 2060)	0.24915048132454623
  (3, 5005)	0.3169028431039865
  (3, 7248)	0.23571908490908416
  (3, 300)	0.2915969875465198
  :	:
  (4454, 4627)	0.3831814754124698
  (4454, 311)	0.19547195974237946
  (4454, 5068)	0.22284357632450164
  (4454, 1094)	0.24862733340971144
  (4454, 1575)	0.20946314330145205
  (4454, 666)	0.28653660324238944
  (4454, 2244)	0.2526916142542512
  (4454, 7084)	0.2689097965804433
  (4454, 571)	0.3005277868014621
  (4454, 5077)	0.3005277868014621
  (4454, 297)	0.3005277868014621
  (4455, 3084)	0.3019392955127119
  (4455, 4614)	0.4677148905542796
  (4455, 3701)	0.546620099025937
  (4455, 7075)	0.6255253074975946
  (4456, 6575)	0.15362974460832007
  (4456, 5820)	0.18767970267638426
  (4456, 7376)	0.20404881687716278
  (4456, 7033)	0.43304344994724825
  (4456, 380)	0.24893867331233713
  (4456, 2509)	0.20620887737471993
  (4456, 7032)	0.2868954144677231
  (4456, 909)	0.26924653489772427
  (4456, 5009)	0.6018082365591317
  (4456, 3768)	0.30090411827956587

In [79]:
model= LogisticRegression()

In [80]:
model.fit(X_train_features,Y_train)

LogisticRegression()

In [81]:
#prediction on training data
predicted_training_values = model.predict(X_train_features)
training_accuracy = accuracy_score(Y_train,predicted_training_values)

In [82]:
print(training_accuracy)

0.9685887368184878

In [83]:
#prediction on testing data
predicted_testing_values = model.predict(X_test_features)
training_accuracy = accuracy_score(Y_test,predicted_testing_values)

In [84]:
print(training_accuracy)

0.9533632286995516

Building a predictive system

In [89]:
from scipy.spatial import transform
input_mail= ["Here's something most students don't know:The best internships are never posted publicly. They go to whoever reached out first — directly to the founder or hiring manager — before anyone else even knew the role existed."]

#converting text into features
input_mail_features = feature_extraction.transform(input_mail)

prediction = model.predict(input_mail_features)

print(prediction)

if(prediction==1):
    print('ham mail')

else:
    print('spam mail')

[1]
ham mail